<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/01/20 09:14:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=portfolio',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
